# Generated by Django 4.2.1 on 2023-05-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_alter_pool_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
