# Generated by Django 4.2.1 on 2023-05-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
