# Generated by Django 4.2.1 on 2023-06-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_userleague'),
        ('accounts', '0002_customuser_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='leagues',
            field=models.ManyToManyField(through='pools.UserLeague', to='pools.league'),
        ),
    ]
